import { Client } from './types';

// Real client data — The Unicorn Realtors / Laura Rao
// Last_contact = days since last contact as of app launch (2026-05-25)

export const SELLERS: Client[] = [
  {
    id: 's1',
    name: 'Angie Winters',
    address: '233 Grand Vista, Dayton',
    price: '$185K',
    last_contact: 58,
    status: 'active',
    current_stage: 4, // Photos
    next_action: 'Pricing strategy CMA · recoup reno costs',
    agent: 'Laura',
    source: 'Sphere',
    entered_stage: 28,
    type: 'seller',
  },
  {
    id: 's2',
    name: 'Max Diaz',
    address: '225 Stingley Rd, Greenville',
    price: '$85K',
    last_contact: 63,
    status: 'active',
    current_stage: 3, // Reno Prep
    next_action: 'Listing prep + photography · confirm April timeline',
    agent: 'Laura',
    source: 'Sphere',
    entered_stage: 30,
    type: 'seller',
  },
  {
    id: 's3',
    name: 'Isaias Sanchez',
    address: '822 Sunlight, Dayton',
    price: '$95K',
    last_contact: 62,
    status: 'active',
    current_stage: 3, // Reno Prep
    next_action: 'Get second HVAC quote · confirm plumbing permit',
    agent: 'Laura',
    source: 'Referral',
    entered_stage: 40,
    type: 'seller',
  },
  {
    id: 's4',
    name: 'Wayne & Yuko Mcghie',
    address: '292 Parrott Ct, Fairborn',
    price: '$245K',
    last_contact: 76,
    status: 'warming',
    current_stage: 2, // Comps / Pricing
    next_action: 'Feedback on Shagbark showing · buy-sell trigger',
    agent: 'Laura',
    source: 'Sphere',
    entered_stage: 30,
    type: 'seller',
  },
  {
    id: 's5',
    name: 'Allison Moody',
    address: "Dad's house, Washington Township",
    price: '$200K',
    last_contact: 71,
    status: 'active',
    current_stage: 0, // Lead
    next_action: 'Visit Washington Township house · contractor quote',
    agent: 'Laura',
    source: 'Sphere',
    entered_stage: 71,
    type: 'seller',
  },
  {
    id: 's6',
    name: 'Dawn Johnson',
    address: '5704 Spring Gate Ct, Huber Heights',
    price: '$170K',
    last_contact: 48,
    status: 'warming',
    current_stage: 0, // Lead
    next_action: "Text Abby → classic car storage or sale",
    agent: 'Laura',
    source: 'Tax pop-up',
    entered_stage: 48,
    type: 'seller',
  },
  {
    id: 's7',
    name: 'Laura Curliss',
    address: 'Probate attorney · estate referrals',
    price: 'Est. $250K+',
    last_contact: 76,
    status: 'warming',
    current_stage: 0, // Lead
    next_action: 'Follow up — stay useful · estate transition partner',
    agent: 'Laura',
    source: 'Panama lien referral',
    entered_stage: 76,
    type: 'seller',
  },
];

export const BUYERS: Client[] = [
  {
    id: 'b1',
    name: 'Liz Robertson',
    address: 'Yellow Springs · 345 E Enon Rd',
    price: '$265K',
    last_contact: 47,
    status: 'active',
    current_stage: 5, // Under Contract
    next_action: 'Waiting on seller response · 345 E Enon Rd',
    agent: 'Laura',
    source: 'Friend',
    entered_stage: 47,
    type: 'buyer',
  },
  {
    id: 'b2',
    name: 'Sarah & Zlatomir',
    address: 'Yellow Springs forever home',
    price: '~$450K',
    last_contact: 47,
    status: 'active',
    current_stage: 1, // Consultation
    next_action: 'Meeting April 11 · prep discovery questions for both',
    agent: 'Laura',
    source: 'YS referral',
    entered_stage: 14,
    type: 'buyer',
  },
  {
    id: 'b3',
    name: 'Luciana Lieff',
    address: 'Budget $275K · Beavercreek/township',
    price: '$275K',
    last_contact: 63,
    status: 'active',
    current_stage: 3, // Actively Showing
    next_action: 'Feedback on Graham/Crestmont/Glenview · MLS auto-search',
    agent: 'Laura',
    source: 'YS village referral',
    entered_stage: 20,
    type: 'buyer',
  },
  {
    id: 'b4',
    name: 'Rubén Darío Intriago',
    address: 'Budget $225K · Huber/Dayton',
    price: '$225K',
    last_contact: 68,
    status: 'active',
    current_stage: 3, // Actively Showing
    next_action: 'Tour houses this week · find his house',
    agent: 'Laura',
    source: 'Referral · Carla',
    entered_stage: 30,
    type: 'buyer',
  },
  {
    id: 'b5',
    name: 'Wayne & Yuko Mcghie',
    address: 'Budget ~$350K · buy-sell',
    price: '~$350K',
    last_contact: 76,
    status: 'warming',
    current_stage: 3, // Actively Showing
    next_action: 'Set up Homes.com AI search · Shagbark feedback',
    agent: 'Laura',
    source: 'Sphere',
    entered_stage: 20,
    type: 'buyer',
  },
  {
    id: 'b6',
    name: 'Jacqueline Voss',
    address: 'Budget ~$1M · horse farm SE OH',
    price: '~$1M',
    last_contact: 85,
    status: 'warming',
    current_stage: 1, // Consultation
    next_action: 'Call Emily (horse specialist) · MLS alert horse farms',
    agent: 'Laura',
    source: 'Zillow / followed from CB',
    entered_stage: 55,
    type: 'buyer',
  },
  {
    id: 'b7',
    name: 'Brian',
    address: 'Budget ~$400K · Centerville→YS',
    price: '~$400K',
    last_contact: 85,
    status: 'warming',
    current_stage: 0, // Lead
    next_action: 'Strategy call · YS vs Centerville 3 paths',
    agent: 'Laura',
    source: 'Referral · Nate',
    entered_stage: 85,
    type: 'buyer',
  },
  {
    id: 'b8',
    name: 'Adrian & Maggie Shergill',
    address: 'Budget $265K · character home',
    price: '$265K',
    last_contact: 99,
    status: 'warming',
    current_stage: 0, // Lead
    next_action: 'Find quirky character home with garden · Birchall energy',
    agent: 'Laura',
    source: 'Sphere',
    entered_stage: 99,
    type: 'buyer',
  },
  {
    id: 'b9',
    name: 'Danielle Lyons',
    address: 'Budget $250K · Beavercreek/Xenia',
    price: '$250K',
    last_contact: 113,
    status: 'cold',
    current_stage: 0, // Lead
    next_action: 'Clarify financing after uncle backed out',
    agent: 'Laura',
    source: 'Homefull referral',
    entered_stage: 113,
    type: 'buyer',
  },
  {
    id: 'b10',
    name: 'Yolraime Rianos',
    address: 'Budget $225K · Dayton · ES',
    price: '$225K',
    last_contact: 99,
    status: 'cold',
    current_stage: 0, // Lead
    next_action: 'Follow up with Jessica on pre-approval · 6mo',
    agent: 'Laura',
    source: 'Referral · Rubén',
    entered_stage: 99,
    type: 'buyer',
  },
];
